version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sagyam/grid-sync-api
    container_name: grid-sync-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://sagyam:1234@mongo:27017/grid-sync-db
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sagyam
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./mongo-data:/data/db
